/*
 * This is sample code generated by rpcgen.
 * hese are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "string.h"
#include "calcul.h"
CLIENT *clnt;

char * getBallon (char* idRobot) {
	reponse *resultat;
	data parametre;
	parametre.arg1 = idRobot;
	resultat = calcul_my_strcat_1 (&parametre, clnt); 
	return resultat->ballon;
}//concatenate


void
calcul_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *calcul_null_1_arg;
	reponse  *result_2;
	data  calcul_my_strcat_1_arg;
#ifndef	DEBUG
	clnt = clnt_create (host, CALCUL, VERSION_UN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = calcul_null_1((void*)&calcul_null_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = calcul_my_strcat_1(&calcul_my_strcat_1_arg, clnt);
	if (result_2 == (reponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char idRobot[30];
	char *pos;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	clnt = clnt_create (host, CALCUL, VERSION_UN, "tcp"); 
	printf("Numéro du robot : ");
	fgets(idRobot,30,stdin);
	if ((pos=strchr(idRobot, '\n')) != NULL) *pos = '\0';
	printf("Ballon généré = %s\n", getBallon(idRobot));
	exit (0);
}
