/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCUL_H_RPCGEN
#define _CALCUL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	char *arg1;
};
typedef struct data data;


struct reponse {
	char *ballon;
	int errno;
};
typedef struct reponse reponse;


#define CALCUL 0x20000001
#define VERSION_UN 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCUL_NULL 0
extern  void * calcul_null_1(void *, CLIENT *);
extern  void * calcul_null_1_svc(void *, struct svc_req *);
#define CALCUL_MY_STRCAT 1
extern  reponse * calcul_my_strcat_1(data *, CLIENT *);
extern  reponse * calcul_my_strcat_1_svc(data *, struct svc_req *);
extern int calcul_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCUL_NULL 0
extern  void * calcul_null_1();
extern  void * calcul_null_1_svc();
#define CALCUL_MY_STRCAT 1
extern  reponse * calcul_my_strcat_1();
extern  reponse * calcul_my_strcat_1_svc();
extern int calcul_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_reponse (XDR *, reponse*);
extern  bool_t xdr_reponse (XDR *, reponse*);

#else /* K&R C */
extern bool_t xdr_data ();
extern bool_t xdr_data ();
extern bool_t xdr_reponse ();
extern bool_t xdr_reponse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCUL_H_RPCGEN */
