/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALLBACK_H_RPCGEN
#define _CALLBACK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CALLBACK_SEMAPHORE 0x20222345
#define V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define grant 9
extern  int * grant_1(int *, CLIENT *);
extern  int * grant_1_svc(int *, struct svc_req *);
extern int callback_semaphore_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define grant 9
extern  int * grant_1();
extern  int * grant_1_svc();
extern int callback_semaphore_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALLBACK_H_RPCGEN */
