/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_semaphore.h"

bool_t
xdr_int_and_counter_t (XDR *xdrs, int_and_counter_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->amount))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->server_counter))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_down_arg_t (XDR *xdrs, down_arg_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->amount))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->server_counter))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->client_id))
		 return FALSE;
	return TRUE;
}
