/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "callback.h"
#include <memory.h>

static struct timeval TIMEOUT = { 25, 0 };

int *
grant_1(int *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, grant,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void
callback_semaphore_1(char *host, int client_id)
{
	CLIENT *clnt;
	int  *result_1;
	int  grant_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALLBACK_SEMAPHORE, V1 + client_id, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = grant_1(&grant_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

////svc_run ();
//	fd_set readfs;
//	readfs = svc_fdset;
//	switch (select(32, &readfs, NULL, NULL, NULL)) {
//		//case -1:
//		//	if (errno == EINTR) {
//		//		continue;
//		//	}
//		//	perror("rstat: select");
//		//	return;
//		//case 0:
//		//	break;
//		default:
//			svc_getreqset(&readfs);
//	}


//int
//main (int argc, char *argv[])
//{
//	char *host;
//
//	if (argc < 2) {
//		printf ("usage: %s server_host\n", argv[0]);
//		exit (1);
//	}
//	host = argv[1];
//	callback_semaphore_1 (host);
//exit (0);
//}
