/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_semaphore.h"
#include "rpc_semaphore_server.c"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
rpc_semaphore_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int_and_counter_t up_1_arg;
		down_arg_t down_1_arg;
		int_and_counter_t set_1_arg;
		int get_server_counter_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case up:
		_xdr_argument = (xdrproc_t) xdr_int_and_counter_t;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) up_1_svc;
		break;

	case down:
		_xdr_argument = (xdrproc_t) xdr_down_arg_t;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) down_1_svc;
		break;

	case set:
		_xdr_argument = (xdrproc_t) xdr_int_and_counter_t;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) set_1_svc;
		break;

	case get_server_counter:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) get_server_counter_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	//if (rqstp->rq_proc == down) {
	sleep(2);
	pop_if();
	//}
	return;
}

int
main (int argc, char **argv)
{
	TAILQ_INIT(&head);
	register SVCXPRT *transp;

	pmap_unset (RPC_SEMAPHORE, V1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, RPC_SEMAPHORE, V1, rpc_semaphore_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RPC_SEMAPHORE, V1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, RPC_SEMAPHORE, V1, rpc_semaphore_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RPC_SEMAPHORE, V1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
